general:
  logTensorboardEvents: true
  loggingConfig: "./config/logging.yml"
  name: "lstm"
  outputDir: "./output"
  saveModel: true
  saveCheckpoints: true
  seed: 42
data:
  basinsFile: "./config/basins.txt"
  forcings:
    - dir: "./data/forcings"
      type: "camels-us"
      variables:
        - "prcp(mm/day)"
        - "tmin(C)"
        - "tmax(C)"
        - "srad(W/m2)"
        - "vp(Pa)"
  streamflow:
    dir: "./data/streamflow"
    type: "camels-us"
    variables:
      - "streamflow"
  training:
    startDate: "1980-01-01"
    endDate: "2003-12-31"
  validation:
    startDate: "2004-01-01"
    endDate: "2009-12-31"
  test:
    startDate: "2010-01-01"
    endDate: "2014-12-31"
model:
  type: "lstm"
  timesteps:
    - 20
  offset: 1
  loss:
    - "mse"
  metrics:
    - "mse"
    - "mae"
  optimizer: "Adam"
  epochs: 10
  batchSize: 32
  multiOutput: false
  params:
    lstm:
      hiddenLayers: 2
      units:
        - 32
        - 32
      dropout:
        - 0.1
        - 0